INSERT INTO USERS (ID, USERNAME, PASSWORD, RATING, ROLE, BALANCE)
VALUES (0, 'admin','admin',  0.0, 'ADMIN', 0);
INSERT INTO USERS (ID, USERNAME, PASSWORD, RATING, ROLE, BALANCE)
VALUES (10, 'Kovács Péter','petike',  0.0, 'USER', 4000);
INSERT INTO USERS (ID, USERNAME, PASSWORD, RATING, ROLE, BALANCE)
VALUES (12, 'Nagy Gábor','gaboo',  0.0, 'USER', 4000);

